export const GET_SENTENCES_REQUEST = 'GET_SENTENCES_REQUEST';
export const GET_SENTENCES_SUCCESS = 'GET_SENTENCES_SUCCESS';
export const GET_SENTENCES_FAIL = 'GET_SENTENCES_FAIL';
export const REMOVE_ONE_SENTENCE = 'REMOVE_ONE_SENTENCE';

export const SEND_VIDEO_REQUEST = 'SEND_VIDEO_REQUEST';
export const SEND_VIDEO_SUCCESS = 'SEND_VIDEO_SUCCESS';
export const SEND_VIDEO_FAIL = 'SEND_VIDEO_FAIL';
